#cloud-config-mkdocs-system

groups:
  - ubuntu: [root,sys]
  - dpro42-group

users:
  - default
  - name: spiderman
    gecos: Peter Parker
    shell: /bin/bash
    primary_group: dpro42-group
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAXLzxwEZxvz5nqOyV1Ey9iraR2vd74LvvTGgULxib8VXx2k4otDgBc7HblvmmS7RSRRdLI32H0jvGP2muM50i+jf2yqM2xtlYFdHKXRRKI/NSa7GArNXdHxUfPUvkX1DthM/ZO+DO2EU2aq9CD6WBK48/hg9pNNq7JI54sl71jnujRz5nzCv9FIGVky5jH0HJM3E20QKrjIXEtTDZ2kHdOwT60Fo+hJ+ceQc2pkM3HsXnllb00Hlshik6Bf6ik7Off/+uITujzMbwwwv1LrpHgznqbdRoqzX6Vs++cjiYzDzWH/u/7AikwrtK7xWW5xTmISQJumryaFvGLOIu5lpGqEa9SgCyqMzKpXwueYjA9u9QNqYbxODBYRIx0QIBa6FM8gL6a35WYcVwS8eppIC/uO7SzlYOG9cxNZchgFmSr6xXAfSWXevTuPY/8NA2SOoJ9TB1RaNulHN7P+xt6Vb01YzX9VUfr3MMgzWKJVweBYOA+GOG4lAi1mnxdCSAess= root@7DeadlySins

runcmd:
  - touch /home/spiderman/hello.txt
  - echo "Hello! and welcome to this server! Destroy me when you are done!" >> /home/spiderman/hello.txt
  - sudo apt-get update
  - sudo apt install apache2 -q -y
  - sudo apt install python3-pip -y
  - sudo pip install mkdocs
  - sudo mkdir /home/spiderman/mkdocs
  - cd /home/spiderman/mkdocs
  - sudo mkdocs new mkdocs-project
  - cd mkdocs-project
  - sudo mkdocs build
  - sudo rm /var/www/html/index.html
  - sudo cp -R site/* /var/www/html
  - sudo systemctl restart apache2
  